version: '2'
services:
  db:
    restart: always
    image: 'postgres'
    expose:
      - "5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=pank 
      - POSTGRES_PASSWORD=pank0211
      - POSTGRES_NAME=postgres
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
    
  app:
    restart: always
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - /var/www/teamspeak
    links:
      - db
    expose:
      - "3000"

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "80:80"

