# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34e57101be67fde9665da8fd1a83152bf21fc91d51962e0f54929e45587722b6b79ad4726e5b26c5b360ac1678e62c8109c8d5049371ab51d81f9fcca199b995
  admin_list: ['linkinpark02111@mail.ru', 'maks2x2@mail.ru']


test:
  secret_key_base: c631913c6702508c2128681ee3dfaa3f456e1f218050751caf3c4dbc8a31f91a86d494a508602f7f6f292decbc882c53a06694922aa1e2fa4f7ad199904ec3db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
