development: &defaults
  w1:
    merchant_id: '123641701293'
    signature: 'longsignature'
  teamspeak:
    login: 'serveradmin'
    password: 'ZsXajlhE'
    #password: '3Z9OOU5e'
    ts_path: '/var/www/tsserver'
  other:
    admin_list: ['linkinpark02111@mail.ru', 'maks2x2@mail.ru']
    ip: 'localhost'
  unitpay:
    public_key: 'key'
    secret_key: 'key'



staging:
  <<: *defaults

production:
  <<: *defaults