development: &defaults
  w1:
    merchant_id: '123641701293'
    signature: 'longsignature'
  teamspeak:
    login: 'serveradmin'
    password: 'fIKUs4uC'
    ts_path: '/home/pank/Desktop/teamspeak'
  other:
    admin_list: ['linkinpark02111@mail.ru', 'maks2x2@mail.ru']
    ip: '127.0.0.1'
  unitpay:
    public_key: 'key'
    secret_key: 'key'



staging:
  <<: *defaults

production:
  <<: *defaults