development: &defaults
  w1:
    merchant_id: '123456789012'
    signature: 'longsignature'
    service_url: 'https://merchant.w1.ru/checkout/default.aspx'
  teamspeak:
    login: 'serveradmin'
    password: 'fIKUs4uC'
    ts_path: '/home/pank/Desktop/teamspeak'
  other:
    admin_list: ['linkinpark02111@mail.ru', 'maks2x2@mail.ru']
    ip: '127.0.0.1'



staging:
  <<: *defaults

production:
  <<: *defaults